
function showimage() {
  document.getElementById('txt').style.display="none"
  document.getElementById('chinaflag').style.display="none"
  document.getElementById('polandflag').style.display="none"
  document.getElementById('franceflag').style.display="none"
  document.getElementById('spainflag').style.display="block"
  document.getElementById('japanflag').style.display="none"
  document.getElementById('name').innerText="Spain"
  document.getElementById('c2').style.borderBlockEndWidth="8px"
  document.getElementById('c2').style.borderColor="rgb(260,0,0)"
  document.getElementById('c3').style.borderColor="#626d7e"
  document.getElementById('c4').style.borderColor="#626d7e"
}
function showimage1() {
  document.getElementById('txt').style.display="none"
  document.getElementById('chinaflag').style.display="none"
  document.getElementById('polandflag').style.display="none"
  document.getElementById('spainflag').style.display="none"
  document.getElementById('franceflag').style.display="block"
  document.getElementById('japanflag').style.display="none"
  document.getElementById('name').innerText="France"
  document.getElementById('c2').style.borderBlockEndWidth="8px"
  document.getElementById('c2').style.borderColor="rgb(220,0,0)"
  document.getElementById('c3').style.borderColor="#626d7e"
  document.getElementById('c4').style.borderColor="#626d7e"
}
function showimage2() {
  document.getElementById('txt').style.display="none"
  document.getElementById('chinaflag').style.display="none"
  document.getElementById('franceflag').style.display="none"
  document.getElementById('spainflag').style.display="none"
  document.getElementById('polandflag').style.display="block"
  document.getElementById('japanflag').style.display="none"
  document.getElementById('name').innerText="Poland"
  document.getElementById('c2').style.borderBlockEndWidth="8px"
  document.getElementById('c2').style.borderColor="rgb(180,0,0)"
  document.getElementById('c3').style.borderColor="#626d7e"
  document.getElementById('c4').style.borderColor="#626d7e"
}
function showimage3() {
  document.getElementById('txt').style.display="none"
  document.getElementById('franceflag').style.display="none"
  document.getElementById('spainflag').style.display="none"
  document.getElementById('polandflag').style.display="none"
  document.getElementById('chinaflag').style.display="block"
  document.getElementById('japanflag').style.display="none"
  document.getElementById('name').innerText="China"
  document.getElementById('c2').style.borderBlockEndWidth="8px"
  document.getElementById('c2').style.borderColor="rgb(140,0,0)"
  document.getElementById('c3').style.borderColor="#626d7e"
  document.getElementById('c4').style.borderColor="#626d7e"
}
function showimage4() {
  document.getElementById('txt').style.display="none"
  document.getElementById('chinaflag').style.display="none"
  document.getElementById('polandflag').style.display="none"
  document.getElementById('franceflag').style.display="none"
  document.getElementById('spainflag').style.display="none"
  document.getElementById('japanflag').style.display="block"
  document.getElementById('name').innerText="Japan"
  document.getElementById('c2').style.borderBlockEndWidth="8px"
  document.getElementById('c2').style.borderColor="rgb(100,0,0)"
  document.getElementById('c3').style.borderColor="#626d7e"
  document.getElementById('c4').style.borderColor="#626d7e"
}
function showimage5() {
  document.getElementById('txt1').style.display = "none"
  document.getElementById('americaflag').style.display = "block"
  document.getElementById('moldovaflag').style.display = "none"
  document.getElementById('italyflag').style.display = "none"
  document.getElementById('indiaflag').style.display = "none"
  document.getElementById('greeceflag').style.display = "none"
  document.getElementById('name').innerText="America"
  document.getElementById('c3').style.borderBlockEndWidth="8px"
  document.getElementById('c3').style.borderColor="rgb(260,0,0)"
  document.getElementById('c2').style.borderColor="#626d7e"
  document.getElementById('c4').style.borderColor="#626d7e"
}
function showimage6() {
  document.getElementById('txt1').style.display = "none"
  document.getElementById('americaflag').style.display = "none"
  document.getElementById('moldovaflag').style.display = "block"
  document.getElementById('italyflag').style.display = "none"
  document.getElementById('indiaflag').style.display = "none"
  document.getElementById('greeceflag').style.display = "none"
  document.getElementById('name').innerText="Moldova"
  document.getElementById('c3').style.borderBlockEndWidth="8px"
  document.getElementById('c3').style.borderColor="rgb(220,0,0)"
  document.getElementById('c2').style.borderColor="#626d7e"
  document.getElementById('c4').style.borderColor="#626d7e"
}
function showimage7() {
  document.getElementById('txt1').style.display = "none"
  document.getElementById('americaflag').style.display = "none"
  document.getElementById('moldovaflag').style.display = "none"
  document.getElementById('italyflag').style.display = "block"
  document.getElementById('indiaflag').style.display = "none"
  document.getElementById('greeceflag').style.display = "none"
  document.getElementById('name').innerText="Italy"
  document.getElementById('c3').style.borderBlockEndWidth="8px"
  document.getElementById('c3').style.borderColor="rgb(180,0,0)"
  document.getElementById('c2').style.borderColor="#626d7e"
  document.getElementById('c4').style.borderColor="#626d7e"
}
function showimage8() {
  document.getElementById('txt1').style.display = "none"
  document.getElementById('americaflag').style.display = "none"
  document.getElementById('moldovaflag').style.display = "none"
  document.getElementById('italyflag').style.display = "none"
  document.getElementById('indiaflag').style.display = "block"
  document.getElementById('greeceflag').style.display = "none"
  document.getElementById('name').innerText="India"
  document.getElementById('c3').style.borderBlockEndWidth="8px"
  document.getElementById('c3').style.borderColor="rgb(140,0,0)"
  document.getElementById('c2').style.borderColor="#626d7e"
  document.getElementById('c4').style.borderColor="#626d7e"
}
function showimage9() {
  document.getElementById('txt1').style.display = "none"
  document.getElementById('americaflag').style.display = "none"
  document.getElementById('moldovaflag').style.display = "none"
  document.getElementById('italyflag').style.display = "none"
  document.getElementById('indiaflag').style.display = "none"
  document.getElementById('greeceflag').style.display = "block"
  document.getElementById('name').innerText="Greece"
  document.getElementById('c3').style.borderBlockEndWidth="8px"
  document.getElementById('c3').style.borderColor="rgb(100,0,0)"
  document.getElementById('c2').style.borderColor="#626d7e"
  document.getElementById('c4').style.borderColor="#626d7e"
}
function showimage10() {
  document.getElementById('txt2').style.display = "none"
  document.getElementById('switzerlandflag').style.display = "block"
  document.getElementById('belgiumflag').style.display = "none"
  document.getElementById('germanyflag').style.display = "none"
  document.getElementById('irelandflag').style.display = "none"
  document.getElementById('finlandflag').style.display = "none"
  document.getElementById('name').innerText="Switzerland"
  document.getElementById('c4').style.borderBlockEndWidth="8px"
  document.getElementById('c4').style.borderColor="rgb(260,0,0)"
  document.getElementById('c2').style.borderColor="#626d7e"
  document.getElementById('c3').style.borderColor="#626d7e"
}
function showimage11() {
  document.getElementById('txt2').style.display = "none"
  document.getElementById('switzerlandflag').style.display = "none"
  document.getElementById('belgiumflag').style.display = "block"
  document.getElementById('germanyflag').style.display = "none"
  document.getElementById('irelandflag').style.display = "none"
  document.getElementById('finlandflag').style.display = "none"
  document.getElementById('name').innerText="Belgium"
  document.getElementById('c4').style.borderBlockEndWidth="8px"
  document.getElementById('c4').style.borderColor="rgb(220,0,0)"
  document.getElementById('c2').style.borderColor="#626d7e"
  document.getElementById('c3').style.borderColor="#626d7e"
}
function showimage12() {
  document.getElementById('txt2').style.display = "none"
  document.getElementById('switzerlandflag').style.display = "none"
  document.getElementById('belgiumflag').style.display = "none"
  document.getElementById('germanyflag').style.display = "block"
  document.getElementById('irelandflag').style.display = "none"
  document.getElementById('finlandflag').style.display = "none"
  document.getElementById('name').innerText="Germany"
  document.getElementById('c4').style.borderBlockEndWidth="8px"
  document.getElementById('c4').style.borderColor="rgb(180,0,0)"
  document.getElementById('c2').style.borderColor="#626d7e"
  document.getElementById('c3').style.borderColor="#626d7e"
}
function showimage13() {
  document.getElementById('txt2').style.display = "none"
  document.getElementById('switzerlandflag').style.display = "none"
  document.getElementById('belgiumflag').style.display = "none"
  document.getElementById('germanyflag').style.display = "none"
  document.getElementById('irelandflag').style.display = "block"
  document.getElementById('finlandflag').style.display = "none"
  document.getElementById('name').innerText="Ireland"
  document.getElementById('c4').style.borderBlockEndWidth="8px"
  document.getElementById('c4').style.borderColor="rgb(140,0,0)"
  document.getElementById('c2').style.borderColor="#626d7e"
  document.getElementById('c3').style.borderColor="#626d7e"
}
function showimage14() {
  document.getElementById('txt2').style.display = "none"
  document.getElementById('switzerlandflag').style.display = "none"
  document.getElementById('belgiumflag').style.display = "none"
  document.getElementById('germanyflag').style.display = "none"
  document.getElementById('irelandflag').style.display = "none"
  document.getElementById('finlandflag').style.display = "block"
  document.getElementById('name').innerText="Finland"
  document.getElementById('c4').style.borderBlockEndWidth="8px"
  document.getElementById('c4').style.borderColor="rgb(100,0,0)"
  document.getElementById('c2').style.borderColor="#626d7e"
  document.getElementById('c3').style.borderColor="#626d7e"
}
function refresh(){
  window.location.reload();
}
